pages:
  stage: deploy
  image: mcr.microsoft.com/playwright:v1.12.3-focal
  script:
  # GitHub Actions unfortunately does not support retries;
  # this is a cumbersome method of retrying twice in case of errors:
  - npx feed-me-up-scotty | npx feed-me-up-scotty | npx feed-me-up-scotty
  artifacts:
    paths:
    - public
    expire_in: 1 day
  only:
  - main
  retry:
    # Sometimes a website is temporarily slow/down:
    max: 2
    when: always
