[22737]
title = "点燃我，温暖你"
url = "https://www.bdys01.com/guoju/22737.htm"
entrySelector = "#torrent-list ul > li"
titleSelector = "div div a"
linkSelector = "div div a"

[22756]
title = "卿卿日常"
url = "https://www.bdys01.com/guoju/22756.htm"
entrySelector = "#torrent-list ul > li"
titleSelector = "div div a"
linkSelector = "div div a"
